/**
 * 峡谷回响问答题库 — server only (cards-api.js reads it; nothing under src/ may import it,
 * or the answers ship to every browser). Source: 桌面/撸撸卡/峡谷回响/问答/回响问答_50题.md,
 * question 58 left out (not certain enough); q59–q101 added 2026-10-04 for the 每日一题 (bank of 100). `answer` is the index of the right option.
 * Rules: src/engine/echoQuiz.ts.
 */
export const ECHO_QUIZ = [
  {"id": "q01", "about": "Uzi", "q": "Uzi 的真实姓名是？", "options": ["简自豪", "简自强", "简俊豪", "简志豪"], "answer": 0},
  {"id": "q02", "about": "Uzi", "q": "Uzi 在 S3、S4 连续两年打进世界赛决赛，当时效力的是哪个战队？", "options": ["OMG", "皇族", "WE", "RNG"], "answer": 1},
  {"id": "q03", "about": "Bengi / PoohManDu / Piglet", "q": "S3 世界赛决赛，SKT 击败的对手是？", "options": ["OMG", "Fnatic", "皇族", "NaJin 黑剑"], "answer": 2},
  {"id": "q04", "about": "Mata / Looper / DanDy / PawN / imp", "q": "S4 世界赛决赛，三星白队击败了哪支战队？", "options": ["星辰皇族", "三星蓝队", "OMG", "Fnatic"], "answer": 0},
  {"id": "q05", "about": "Mata", "q": "S4 冠军三星白队的辅助是谁？", "options": ["Heart", "PoohManDu", "Wolf", "Mata"], "answer": 3},
  {"id": "q06", "about": "PawN", "q": "S4 夺冠后，PawN 加入了哪支 LPL 战队，并在 2015 年拿下 MSI 冠军？", "options": ["EDG", "OMG", "LGD", "RNG"], "answer": 0},
  {"id": "q07", "about": "Looper", "q": "S4 夺冠后，Looper 在 2015 年加入了哪支 LPL 战队？", "options": ["EDG", "RNG", "iG", "LGD"], "answer": 1},
  {"id": "q08", "about": "imp", "q": "S4 夺冠后，imp 在 2015 年加入了哪支 LPL 战队？", "options": ["LGD", "WE", "OMG", "VG"], "answer": 0},
  {"id": "q09", "about": "DanDy", "q": "S4 夺冠后，DanDy 在 2015 年加入了哪支 LPL 战队？", "options": ["iG", "EDG", "VG（Vici Gaming）", "Snake"], "answer": 2},
  {"id": "q10", "about": "Clearlove", "q": "Clearlove 的中文名是？", "options": ["明凯", "明锴", "名凯", "明恺"], "answer": 0},
  {"id": "q11", "about": "Clearlove / PawN", "q": "2015 年第一届 MSI 决赛，EDG 击败了哪支战队？", "options": ["Fnatic", "TSM", "SKT", "ahq"], "answer": 2},
  {"id": "q12", "about": "Clearlove", "q": "2015 年 MSI 冠军 EDG 的打野是谁？", "options": ["Clearlove", "Mlxg", "Condi", "LoveLing"], "answer": 0},
  {"id": "q13", "about": "MaRin", "q": "S5 世界赛决赛的 MVP 是谁？", "options": ["Bang", "MaRin", "Bengi", "Wolf"], "answer": 1},
  {"id": "q14", "about": "MaRin / Bang / Wolf / Easyhoon", "q": "S5 世界赛决赛，SKT 击败了哪支战队？", "options": ["KOO Tigers", "Fnatic", "Origen", "EDG"], "answer": 0},
  {"id": "q15", "about": "Easyhoon", "q": "S5 时期在 SKT 和 Faker 轮换上场的中单是谁？", "options": ["Crown", "Easyhoon", "Kuro", "PawN"], "answer": 1},
  {"id": "q16", "about": "Bengi", "q": "Bengi 一共拿过几次世界赛冠军？", "options": ["1 次", "2 次", "3 次", "4 次"], "answer": 2},
  {"id": "q17", "about": "Bang / Wolf", "q": "Bang 和 Wolf 这对下路组合一起拿过几次世界赛冠军？", "options": ["1 次", "2 次", "3 次", "0 次"], "answer": 1},
  {"id": "q18", "about": "Duke", "q": "S6 冠军 SKT 的上单是谁？", "options": ["MaRin", "Huni", "Duke", "Smeb"], "answer": 2},
  {"id": "q19", "about": "Duke / Bengi", "q": "S6 世界赛决赛，SKT 击败了哪支战队？", "options": ["ROX Tigers", "三星", "H2K", "C9"], "answer": 1},
  {"id": "q20", "about": "Smeb", "q": "2016 年 Smeb 所在的 ROX Tigers 在 S6 半决赛输给了哪支战队？", "options": ["SKT", "三星", "H2K", "EDG"], "answer": 0},
  {"id": "q21", "about": "Ambition / CuVee / Crown", "q": "S7 世界赛冠军是哪支战队？", "options": ["SKT", "三星", "RNG", "WE"], "answer": 1},
  {"id": "q22", "about": "Ambition", "q": "Ambition 在 CJ 时期打的是哪个位置，后来才转打野？", "options": ["上单", "中单", "下路", "辅助"], "answer": 1},
  {"id": "q23", "about": "Crown", "q": "S7 冠军三星的中单是谁？", "options": ["Crown", "Kuro", "PawN", "Easyhoon"], "answer": 0},
  {"id": "q24", "about": "CuVee", "q": "S7 冠军三星的上单是谁？", "options": ["Smeb", "Looper", "CuVee", "Huni"], "answer": 2},
  {"id": "q25", "about": "Mystic / Ben", "q": "2017 年 WE 在 S7 世界赛最终打进了哪一轮？", "options": ["小组赛", "八强", "四强", "决赛"], "answer": 2},
  {"id": "q26", "about": "Ning / Baolan", "q": "S8 世界赛决赛，iG 击败了哪支战队？", "options": ["G2", "Fnatic", "C9", "KT"], "answer": 1},
  {"id": "q27", "about": "Ning", "q": "S8 世界赛决赛的 MVP 是谁？", "options": ["Ning", "Baolan", "Rookie", "JackeyLove"], "answer": 0},
  {"id": "q28", "about": "Baolan", "q": "S8 冠军 iG 的辅助是谁？", "options": ["Ming", "Baolan", "Ben", "Meiko"], "answer": 1},
  {"id": "q29", "about": "Ning / Baolan", "q": "S8 世界赛决赛在哪个国家举行？", "options": ["中国", "美国", "韩国", "德国"], "answer": 2},
  {"id": "q30", "about": "GimGoon / Lwx", "q": "S9 世界赛决赛，FPX 击败了哪支战队？", "options": ["SKT", "G2", "iG", "Fnatic"], "answer": 1},
  {"id": "q31", "about": "GimGoon", "q": "S9 冠军 FPX 的上单是谁？", "options": ["GimGoon", "Letme", "957", "Xiyang"], "answer": 0},
  {"id": "q32", "about": "Lwx", "q": "S9 冠军 FPX 的下路是谁？", "options": ["Uzi", "Smlz", "Lwx", "iBoy"], "answer": 2},
  {"id": "q33", "about": "Nuguri", "q": "S10 冠军 DWG 的上单是谁？", "options": ["Nuguri", "Smeb", "Huni", "Rascal"], "answer": 0},
  {"id": "q34", "about": "SwordArT / Nuguri", "q": "S10 世界赛决赛，DWG 击败了哪支 LPL 战队？", "options": ["TES", "JDG", "SN（苏宁）", "LGD"], "answer": 2},
  {"id": "q35", "about": "SwordArT", "q": "S10 打进世界赛决赛的苏宁，辅助是谁？", "options": ["SwordArT", "Baolan", "Ming", "COLD"], "answer": 0},
  {"id": "q36", "about": "Deft", "q": "Deft 在 2022 年随哪支战队夺得世界赛冠军？", "options": ["T1", "DRX", "Gen.G", "DK"], "answer": 1},
  {"id": "q37", "about": "Mlxg / Letme", "q": "2018 年 MSI 冠军是哪支战队？", "options": ["RNG", "KZ", "FW", "EG"], "answer": 0},
  {"id": "q38", "about": "PraY / GorillA", "q": "2018 年 MSI 决赛，RNG 击败的韩国战队是？", "options": ["SKT", "KT", "KZ（Kingzone DragonX）", "AFS"], "answer": 2},
  {"id": "q39", "about": "Mlxg", "q": "2018 年 MSI 冠军 RNG 的打野是谁？", "options": ["Clearlove", "Mlxg", "Ning", "Condi"], "answer": 1},
  {"id": "q40", "about": "Perkz / Jankos", "q": "2019 年 MSI 冠军是哪支战队？", "options": ["TL", "G2", "SKT", "iG"], "answer": 1},
  {"id": "q41", "about": "Perkz", "q": "2019 赛季 Caps 加入 G2 后，Perkz 改打哪个位置？", "options": ["上单", "打野", "下路", "辅助"], "answer": 2},
  {"id": "q42", "about": "YellOwStaR", "q": "2015 年 EU LCS 夏季赛，YellOwStaR 所在的 Fnatic 常规赛战绩是多少？", "options": ["16 胜 2 负", "17 胜 1 负", "18 胜 0 负", "15 胜 3 负"], "answer": 2},
  {"id": "q43", "about": "Huni", "q": "Huni 进入 LCK 之前，在哪个赛区打出名气？", "options": ["LPL", "EU LCS（Fnatic）", "NA LCS", "LMS"], "answer": 1},
  {"id": "q44", "about": "Broxah", "q": "S8 打进世界赛决赛的 Fnatic，打野是谁？", "options": ["Jankos", "Broxah", "Shook", "Xerxe"], "answer": 1},
  {"id": "q45", "about": "xPeke", "q": "xPeke 那次著名的单人偷塔，用的是哪位英雄？", "options": ["卡萨丁", "阿卡丽", "劫", "妖姬"], "answer": 0},
  {"id": "q46", "about": "xPeke", "q": "xPeke 退役后创立的战队是？", "options": ["Fnatic", "Misfits", "Origen", "Splyce"], "answer": 2},
  {"id": "q47", "about": "inSec", "q": "以 inSec 命名的招牌操作「回旋踢」，是哪位英雄的？", "options": ["李青", "赵信", "皇子", "武器大师"], "answer": 0},
  {"id": "q48", "about": "Cyanide", "q": "Cyanide 在 2011 年随 Fnatic 拿下了什么冠军？", "options": ["第一届世界赛", "第一届 MSI", "IEM 世界总决赛", "EU LCS 春季赛"], "answer": 0},
  {"id": "q49", "about": "Froggen", "q": "Froggen 最著名的招牌英雄是？", "options": ["艾尼维亚（冰晶凤凰）", "卡牌大师", "狐狸", "发条"], "answer": 0},
  {"id": "q50", "about": "Doublelift", "q": "Doublelift 职业生涯从没效力过下面哪支战队？", "options": ["CLG", "TSM", "TL", "Cloud9"], "answer": 3},
  {"id": "q51", "about": "PDD", "q": "PDD 的真实姓名是？", "options": ["刘谋", "刘谟", "刘牧", "刘默"], "answer": 0},
  {"id": "q52", "about": "Bjergsen", "q": "Bjergsen 来自哪个国家？", "options": ["瑞典", "丹麦", "挪威", "德国"], "answer": 1},
  {"id": "q53", "about": "Sneaky", "q": "经常在直播里女装 cosplay、出了名的 C9 老将下路是谁？", "options": ["Sneaky", "Doublelift", "WildTurtle", "imaqtpie"], "answer": 0},
  {"id": "q54", "about": "Hai", "q": "C9 首个 LCS 赛季（2013 夏季赛）就夺冠，当时的中单兼指挥是谁？", "options": ["Jensen", "Hai", "Bjergsen", "Pobelter"], "answer": 1},
  {"id": "q55", "about": "Dyrus", "q": "Dyrus 长期效力的北美战队是？", "options": ["CLG", "C9", "TSM", "Dignitas"], "answer": 2},
  {"id": "q56", "about": "MadLife", "q": "以机器人、锤石的钩子闻名，被称为「辅助之神」的韩国老将是？", "options": ["Mata", "MadLife", "Wolf", "GorillA"], "answer": 1},
  {"id": "q57", "about": "Diamondprox", "q": "Diamondprox 来自哪个国家？", "options": ["俄罗斯", "波兰", "乌克兰", "瑞典"], "answer": 0},
  {"id": "q59", "about": "Bengi", "q": "Bengi 职业生涯打的是哪个位置？", "options": ["上单", "打野", "中单", "辅助"], "answer": 1},
  {"id": "q60", "about": "PoohManDu", "q": "S3 冠军 SKT 的辅助是谁？", "options": ["Mata", "Wolf", "PoohManDu", "MadLife"], "answer": 2},
  {"id": "q61", "about": "Piglet", "q": "S3 冠军 SKT 的下路是谁？", "options": ["Bang", "Piglet", "imp", "Deft"], "answer": 1},
  {"id": "q62", "about": "MadLife", "q": "MadLife 职业生涯大部分时间效力的是哪支战队？", "options": ["SKT", "KT", "三星", "CJ Entus"], "answer": 3},
  {"id": "q63", "about": "Dade", "q": "S4 打进四强的三星蓝队，中单是谁？", "options": ["Dade", "Faker", "PawN", "Ryu"], "answer": 0},
  {"id": "q64", "about": "Uzi", "q": "Uzi 第一次宣布退役是在哪一年？", "options": ["2019 年", "2020 年", "2021 年", "2022 年"], "answer": 1},
  {"id": "q65", "about": "Uzi / Mlxg / Ming", "q": "2018 年 Uzi 随中国队拿下了哪项综合运动会的英雄联盟金牌？", "options": ["奥运会", "全运会", "亚运会", "东亚运动会"], "answer": 2},
  {"id": "q66", "about": "PDD", "q": "PDD 职业生涯效力的战队是？", "options": ["iG", "OMG", "WE", "皇族"], "answer": 0},
  {"id": "q67", "about": "WeiXiao", "q": "WeiXiao（微笑）是哪支战队的元老下路？", "options": ["iG", "WE", "OMG", "皇族"], "answer": 1},
  {"id": "q68", "about": "Bjergsen", "q": "Bjergsen 第一次退役后，在 TSM 担任了什么职务？", "options": ["主教练", "经理", "老板", "解说"], "answer": 0},
  {"id": "q69", "about": "xPeke", "q": "xPeke 那次著名的单人偷塔，对手是哪支战队？", "options": ["Gambit", "CLG", "SK Gaming", "Moscow Five"], "answer": 2},
  {"id": "q70", "about": "Froggen", "q": "Froggen 来自哪个国家？", "options": ["瑞典", "丹麦", "德国", "挪威"], "answer": 1},
  {"id": "q71", "about": "Diamondprox", "q": "Diamondprox 成名的战队是？", "options": ["Fnatic", "Alliance", "SK Gaming", "Moscow Five"], "answer": 3},
  {"id": "q72", "about": "Alex Ich", "q": "Alex Ich 在 Moscow Five / Gambit 打的是哪个位置？", "options": ["上单", "打野", "中单", "辅助"], "answer": 2},
  {"id": "q73", "about": "YellOwStaR", "q": "YellOwStaR 在 Fnatic 最为人熟知的位置是？", "options": ["上单", "中单", "辅助", "打野"], "answer": 2},
  {"id": "q74", "about": "Huni", "q": "2015 年 Huni 随 Fnatic 在世界赛打进了哪一轮？", "options": ["小组赛", "八强", "四强", "决赛"], "answer": 2},
  {"id": "q75", "about": "Febiven", "q": "2015 年夏季赛 18 胜 0 负的 Fnatic，中单是谁？", "options": ["Caps", "Febiven", "Perkz", "xPeke"], "answer": 1},
  {"id": "q76", "about": "Perkz", "q": "Perkz 离开 G2 后加入了哪支北美战队？", "options": ["TSM", "Team Liquid", "Cloud9", "100 Thieves"], "answer": 2},
  {"id": "q77", "about": "Smeb", "q": "Smeb 效力的 ROX Tigers 在 2016 年拿下了 LCK 哪个赛季的冠军？", "options": ["春季赛", "夏季赛", "两个都拿了", "都没拿"], "answer": 1},
  {"id": "q78", "about": "PraY / GorillA", "q": "PraY 和 GorillA 这对下路组合，2015 年随哪支战队打进了世界赛决赛？", "options": ["SKT", "三星", "KOO Tigers", "KT"], "answer": 2},
  {"id": "q79", "about": "Kuro", "q": "Kuro 在 KOO / ROX Tigers 打的是哪个位置？", "options": ["上单", "打野", "中单", "下路"], "answer": 2},
  {"id": "q80", "about": "Peanut", "q": "Peanut 2016 年在哪支战队拿下 LCK 夏季赛冠军？", "options": ["SKT", "ROX Tigers", "三星", "KT"], "answer": 1},
  {"id": "q81", "about": "Ambition", "q": "Ambition 在 S7 冠军三星打的是哪个位置？", "options": ["上单", "打野", "中单", "辅助"], "answer": 1},
  {"id": "q82", "about": "inSec", "q": "inSec 2014 年随哪支 LPL 战队打进 S4 世界赛决赛？", "options": ["OMG", "EDG", "皇族", "LMQ"], "answer": 2},
  {"id": "q83", "about": "Gogoing", "q": "Gogoing 长期效力的战队是？", "options": ["OMG", "WE", "iG", "EDG"], "answer": 0},
  {"id": "q84", "about": "Letme", "q": "Letme 在 RNG 打的是哪个位置？", "options": ["上单", "打野", "中单", "辅助"], "answer": 0},
  {"id": "q85", "about": "Condi", "q": "2017 年 WE 打进 S7 四强时，Condi 打的是哪个位置？", "options": ["上单", "打野", "中单", "辅助"], "answer": 1},
  {"id": "q86", "about": "Mystic", "q": "S7 打进四强的 WE，下路是谁？", "options": ["Uzi", "iBoy", "Mystic", "Smlz"], "answer": 2},
  {"id": "q87", "about": "iBoy", "q": "iBoy 主要效力的战队是？", "options": ["RNG", "EDG", "OMG", "WE"], "answer": 1},
  {"id": "q88", "about": "Ming", "q": "Ming（史森明）长期效力的战队是？", "options": ["RNG", "EDG", "iG", "FPX"], "answer": 0},
  {"id": "q89", "about": "957", "q": "957 在 WE 打的是哪个位置？", "options": ["上单", "打野", "中单", "下路"], "answer": 0},
  {"id": "q90", "about": "Ben", "q": "S7 打进四强的 WE，辅助是谁？", "options": ["Ming", "Meiko", "Baolan", "Ben"], "answer": 3},
  {"id": "q91", "about": "Cool", "q": "Cool（余家俊）主要效力的战队是？", "options": ["WE", "OMG", "iG", "皇族"], "answer": 1},
  {"id": "q92", "about": "Xpecial", "q": "Xpecial 在 TSM 打的是哪个位置？", "options": ["上单", "中单", "下路", "辅助"], "answer": 3},
  {"id": "q93", "about": "Karsa", "q": "Karsa 在闪电狼（Flash Wolves）打的是哪个位置？", "options": ["上单", "打野", "中单", "辅助"], "answer": 1},
  {"id": "q94", "about": "Maple", "q": "Maple 成名的战队是？", "options": ["闪电狼（Flash Wolves）", "ahq", "J Team", "台北暗杀星"], "answer": 0},
  {"id": "q95", "about": "Levi", "q": "Levi 来自哪个国家？", "options": ["泰国", "越南", "菲律宾", "马来西亚"], "answer": 1},
  {"id": "q96", "about": "brTT", "q": "brTT 来自哪个国家？", "options": ["阿根廷", "墨西哥", "巴西", "智利"], "answer": 2},
  {"id": "q97", "about": "Armut", "q": "Armut 来自哪个国家？", "options": ["土耳其", "希腊", "保加利亚", "罗马尼亚"], "answer": 0},
  {"id": "q98", "about": "Vizicsacsi", "q": "Vizicsacsi 来自哪个国家？", "options": ["波兰", "捷克", "匈牙利", "奥地利"], "answer": 2},
  {"id": "q99", "about": "Mithy", "q": "Mithy 在 G2 打的是哪个位置？", "options": ["上单", "中单", "下路", "辅助"], "answer": 3},
  {"id": "q100", "about": "Spirit", "q": "韩国打野 Spirit 2016 年加入了哪支欧洲战队？", "options": ["G2", "Fnatic", "H2K", "Origen"], "answer": 1},
  {"id": "q101", "about": "Edward", "q": "Edward 在 Moscow Five 打的是哪个位置？", "options": ["上单", "打野", "中单", "辅助"], "answer": 3},
]
