"""Collect each player's club join date from vlr.gg.

Why: two team-mates who have played together for three years know each other
better than either knows the man who arrived in January, and the game had no
way to express that. vlr.gg prints "joined in March 2026" on a player page, so
the overlap between two join dates is exactly the shared tenure we want.

Liquipedia was the first place I looked — its player pages carry a team history
section, but it is generated by {{TeamHistoryAuto}} from their database and is
simply not present in the page source, so there is nothing to parse.

Same rules as the other vlr scraper: >= 3s between requests, abort and save on
429/403, cache merges rather than overwrites.
"""
from __future__ import annotations

import argparse
import gzip
import json
import re
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RAW = ROOT / "data-raw"
SRC = RAW / "vlr_vct2026_players.txt"
CACHE = ROOT / "scripts" / "cache" / "vlr_tenure.json"
VCL_CACHE = ROOT / "scripts" / "cache" / "vlr_challengers.json"

UA = ("ValManagerGameBuild/0.1 (hobby esports-manager project; "
      "contact: yankejing711@gmail.com)")

MIN_INTERVAL = 3.0
_last = 0.0

MONTHS = {m: i + 1 for i, m in enumerate([
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
])}


class RateLimited(RuntimeError):
    pass


def _get(url: str) -> str:
    global _last
    wait = MIN_INTERVAL - (time.monotonic() - _last)
    if wait > 0:
        time.sleep(wait)
    _last = time.monotonic()
    req = urllib.request.Request(
        url, headers={"User-Agent": UA, "Accept-Encoding": "gzip"})
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            raw = r.read()
            if r.headers.get("Content-Encoding") == "gzip":
                raw = gzip.decompress(raw)
            return raw.decode("utf-8", "replace")
    except urllib.error.HTTPError as e:
        if e.code in (429, 403):
            raise RateLimited(f"vlr.gg answered {e.code}. Stopping, progress saved.") from e
        raise


def joined_on(html: str) -> dict | None:
    """The club a player is currently on, and the month they joined it."""
    block = re.search(
        r"Current Teams.*?<div class=\"wf-card\">(.*?)</div>\s*</div>\s*</a>",
        html, re.S)
    if not block:
        return None
    seg = block.group(1)
    team = re.search(r'href="/team/(\d+)/', seg)
    when = re.search(r"joined in\s+([A-Za-z]+)\s+(\d{4})", seg)
    if not team:
        return None
    out = {"teamId": team.group(1)}
    if when:
        out["month"] = MONTHS.get(when.group(1), 1)
        out["year"] = int(when.group(2))
    return out


# The tier-1 source file carries no vlr ids, and team pages do not print join
# dates — only player pages do. So the ids are walked down: region event page ->
# clubs -> squads -> players. Four extra requests to save guessing 240 slugs.
# A stage event only lists the clubs that qualified for it — the China page
# carries 8 of the 12, which is how EDward Gaming went missing entirely. The
# regional ranking pages list every club in the league, so they are the source
# of record here and the events only top it up.
VCT_SOURCES = [
    "https://www.vlr.gg/rankings/americas",
    "https://www.vlr.gg/rankings/europe",
    "https://www.vlr.gg/rankings/asia-pacific",
    "https://www.vlr.gg/rankings/china",
    "https://www.vlr.gg/event/2977/vct-2026-americas-stage-2",
    "https://www.vlr.gg/event/2976/vct-2026-emea-stage-2",
    "https://www.vlr.gg/event/2776/vct-2026-pacific-stage-2",
    "https://www.vlr.gg/event/2978/vct-2026-china-stage-2",
]


def tier1_players(cache: dict) -> dict[str, str]:
    """{ign: vlrId} for every VCT club's current roster."""
    known = cache.setdefault("_teams", {})
    out: dict[str, str] = {}
    teams: dict[str, str] = {}
    for url in VCT_SOURCES:
        for m in re.finditer(r'href="/team/(\d+)/([^"?]+)"', _get(url.rstrip("/") + "/")):
            teams[m.group(1)] = m.group(2)
    print(f"  {len(teams)} clubs found across rankings and events", flush=True)

    for i, (tid, slug) in enumerate(sorted(teams.items()), 1):
        if tid in known:
            out.update(known[tid])
            continue
        html = _get(f"https://www.vlr.gg/team/{tid}/{slug}")
        roster: dict[str, str] = {}
        # the roster block uses team-roster-item-name-alias; text-of on this
        # page is the event list further down, which is what an earlier version
        # of this regex picked up — 44 clubs yielded 7 "players", all event names
        for m in re.finditer(
            r'<div class="team-roster-item">(.*?)</div>\s*</a>', html, re.S,
        ):
            item = m.group(1)
            pid = re.search(r'href="/player/(\d+)/', item)
            alias = re.search(
                r'class="team-roster-item-name-alias"[^>]*>(.*?)</div>', item, re.S)
            if not pid or not alias:
                continue
            name = re.sub(r"<[^>]+>", "", alias.group(1)).strip()
            # staff carry a role tag inside the same card
            if name and not re.search(r"(coach|manager|analyst)", item, re.I):
                roster[name] = pid.group(1)
        known[tid] = roster
        out.update(roster)
        if i % 10 == 0:
            print(f"  [{i}/{len(teams)}] rosters read, {len(out)} players", flush=True)
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--limit", type=int, default=0)
    args = ap.parse_args()

    cache = json.loads(CACHE.read_text("utf-8")) if CACHE.exists() else {}

    # every player we model, with the vlr id we already hold for them
    wanted: dict[str, str] = {}
    if VCL_CACHE.exists():
        vcl = json.loads(VCL_CACHE.read_text("utf-8"))
        for t in vcl.get("teams", {}).values():
            for p in t.get("roster", []):
                if p.get("role") == "player":
                    wanted[p["ign"]] = p["vlrId"]
        for lines in vcl.get("stats", {}).values():
            for r in lines:
                wanted.setdefault(r["ign"], r["vlrId"])
        for r in vcl.get("players", {}).values():
            wanted.setdefault(r["ign"], "")

    try:
        wanted.update(tier1_players(cache))
    except RateLimited as e:
        print(f"!! {e}", file=sys.stderr)

    todo = [(ign, vid) for ign, vid in wanted.items()
            if vid and ign not in cache and not ign.startswith("_")]
    if args.limit:
        todo = todo[: args.limit]
    print(f"cache holds {len(cache)}; {len(todo)} players to read "
          f"(~{len(todo) * MIN_INTERVAL / 60:.1f} min)", flush=True)

    try:
        for i, (ign, vid) in enumerate(todo, 1):
            slug = re.sub(r"[^a-z0-9]+", "-", ign.lower()).strip("-") or "p"
            info = joined_on(_get(f"https://www.vlr.gg/player/{vid}/{slug}"))
            cache[ign] = info or {"miss": True}
            if i % 10 == 0 or i == len(todo):
                CACHE.parent.mkdir(parents=True, exist_ok=True)
                CACHE.write_text(json.dumps(cache, ensure_ascii=False), "utf-8")
                print(f"  [{i}/{len(todo)}] {ign}: "
                      f"{info.get('year') if info else '—'}", flush=True)
    except RateLimited as e:
        print(f"\n!! {e}", file=sys.stderr)
        return 2
    except KeyboardInterrupt:
        print("\ninterrupted — progress saved", file=sys.stderr)

    CACHE.parent.mkdir(parents=True, exist_ok=True)
    CACHE.write_text(json.dumps(cache, ensure_ascii=False), "utf-8")
    hit = sum(1 for k, v in cache.items() if not k.startswith("_") and v.get("year"))
    tot = sum(1 for k in cache if not k.startswith("_"))
    print(f"\ndone. join dates for {hit}/{tot} players -> {CACHE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
