# Generated by DeepSeek V4 Pro; reviewed for strict TLS, URL/path validation,
# UTF-8 output and visible contact-sheet names. Never modifies public assets.
import json, os, sys, time, hashlib, urllib.request, urllib.error, ssl
from pathlib import Path
from datetime import datetime, timezone
from PIL import Image, ImageOps, ImageDraw

BASE = Path('.local-data/portrait-review-v2/reproduced')
MANIFEST_PATH = BASE / 'manifest.json'
CONTACT_SHEET = BASE / 'contact-sheet.png'
DATA_FILE = Path('docs/portrait-audit-20260922.json')
MAX_BYTES = 8 * 1024 * 1024
TIMEOUT = 20
INTERVAL = 1.0
HOST_WHITELIST = {'chaincc.lol', 'cdn.oneesports.gg', 'static.invenglobal.com', 'imgcdn.cna.com.tw'}
USER_AGENT = 'portrait-review-tool/2.0 (research; contact local-admin)'
ctx = ssl.create_default_context()

sys.stdout.reconfigure(encoding="utf-8")
Image.MAX_IMAGE_PIXELS = 20_000_000
log_lines = []

def log(msg):
    ts = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
    line = f'[{ts}] {msg}'
    log_lines.append(line)
    print(line, flush=True)

def safe_name(s):
    return hashlib.md5(str(s).encode('utf-8')).hexdigest()

def is_allowed_host(url):
    from urllib.parse import urlparse
    try:
        parsed = urlparse(url)
        return parsed.scheme == "https" and parsed.hostname in HOST_WHITELIST
    except Exception:
        return False

def fetch_image(url, dest_file, max_bytes=MAX_BYTES):
    if not is_allowed_host(url): return None, "host-blocked"
    opener = urllib.request.build_opener(urllib.request.HTTPSHandler(context=ctx))
    opener.addheaders = [('User-Agent', USER_AGENT), ('Accept', 'image/*')]
    try:
        with opener.open(url, timeout=TIMEOUT) as resp:
            final_url = resp.geturl()
            if not is_allowed_host(final_url):
                log(f'Redirected to disallowed host: {final_url}')
                return None, 'redirect-blocked'
            length = resp.headers.get('Content-Length')
            if length and int(length) > max_bytes:
                log(f'Content-Length too large: {length}')
                return None, 'too-large'
            chunks = []
            total = 0
            while True:
                chunk = resp.read(65536)
                if not chunk:
                    break
                total += len(chunk)
                if total > max_bytes:
                    log('Download exceeded size limit')
                    return None, 'too-large'
                chunks.append(chunk)
            data = b''.join(chunks)
            dest_file.write_bytes(data)
            return len(data), 'ok'
    except urllib.error.HTTPError as e:
        if e.code == 429:
            log('HTTP 429 received; stopping all downloads')
            return None, 'global-stop-429'
        elif e.code == 403:
            log('HTTP 403 forbidden; skipping')
            return None, 'forbidden'
        else:
            log(f'HTTP {e.code} for {url}')
            return None, f'http-{e.code}'
    except urllib.error.URLError as e:
        log(f'URL error: {e.reason}')
        return None, 'url-error'
    except TimeoutError:
        log('Timeout')
        return None, 'timeout'
    except Exception as e:
        log(f'Unexpected error: {e}')
        return None, 'error'

def validate_pil(file_path):
    try:
        with Image.open(file_path) as im:
            im.verify()
        with Image.open(file_path) as im:
            im.load()
            w, h = im.size
            if w < 32 or h < 32:
                return (w, h), 'too-small'
            if w * h > 20_000_000:
                return (w, h), 'too-many-pixels'
            return (w, h), 'ok'
    except Exception as e:
        log(f'PIL verify failed: {e}')
        return (None, None), 'pil-error'

def make_thumb(src_path, dst_path, max_size=(320, 400)):
    try:
        with Image.open(src_path) as im:
            im.load()
            thumb = im.copy()
            thumb.thumbnail(max_size, Image.LANCZOS)
            if thumb.mode in ('RGBA', 'LA') or (thumb.mode == 'P' and 'transparency' in thumb.info):
                thumb = thumb.convert('RGBA')
            elif thumb.mode != 'RGB':
                thumb = thumb.convert('RGB')
            thumb.save(dst_path, format='WEBP', quality=85)
            return True
    except Exception as e:
        log(f'Thumbnail error: {e}')
        return False

def create_contact_sheet(entries):
    thumbnails = []
    for item in entries:
        thumb_path = BASE / 'thumbs' / f"{item['safe_name']}.webp"
        if thumb_path.exists():
            try:
                thumbnails.append((item['name'], Image.open(thumb_path).convert('RGBA')))
            except Exception:
                continue
    if not thumbnails:
        log('No thumbnails for contact sheet')
        return
    cols = min(6, len(thumbnails))
    rows = (len(thumbnails) + cols - 1) // cols
    cell_w, cell_h = 320, 400
    pad = 6
    sheet_w = cols * (cell_w + pad) + pad
    sheet_h = rows * (cell_h + pad) + pad
    sheet = Image.new('RGBA', (sheet_w, sheet_h), (180, 180, 180, 255))
    draw = ImageDraw.Draw(sheet)
    for i, (name, thumb) in enumerate(thumbnails):
        r, c = divmod(i, cols)
        x = pad + c * (cell_w + pad)
        y = pad + r * (cell_h + pad)
        thumb.thumbnail((cell_w, cell_h), Image.LANCZOS)
        tx = x + (cell_w - thumb.width) // 2
        ty = y + (cell_h - thumb.height) // 2
        sheet.alpha_composite(thumb, (tx, ty))
        draw.rectangle((x, y, x + cell_w, y + cell_h), outline=(40, 40, 40, 255), width=1)
        draw.text((x + 4, y + 4), name, fill=(0, 0, 0, 255))
    sheet.convert('RGB').save(CONTACT_SHEET)
    log(f'Contact sheet saved: {CONTACT_SHEET}')

def main():
    BASE.mkdir(parents=True, exist_ok=True)
    (BASE / 'thumbs').mkdir(exist_ok=True)
    try:
        with open(DATA_FILE, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except Exception as e:
        log(f'Failed to load data: {e}')
        sys.exit(1)
    added = data.get('added', [])
    if not isinstance(added, list):
        log('No added array')
        sys.exit(1)
    manifest = {
        'audit_source': str(DATA_FILE),
        'generated_at': datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'),
        'items': []
    }
    stop_all = False
    for idx, item in enumerate(added):
        if stop_all:
            log('Stopping all downloads due to 429')
            break
        url = item.get('sourcePhoto') or {}
        if isinstance(url, dict):
            src_url = url.get('url')
        else:
            src_url = str(url)
        image_name = str(item.get('image', ''))
        if Path(image_name).name != image_name: raise ValueError('Unsafe filename')
        if not src_url or not image_name:
            log(f'Item {idx} missing url/image')
            continue
        safe = safe_name(image_name)
        dest_file = BASE / image_name
        thumb_dest = BASE / 'thumbs' / f'{safe}.webp'
        entry = {
            'safe_name': safe,
            'image': image_name,
            'source_page': item.get('sourcePage'),
            'kind': item.get('kind'),
            'name': item.get('name'),
            'source_url': src_url,
            'status': 'pending',
            'width': None,
            'height': None,
            'bytes': None,
            'note': ''
        }
        if dest_file.exists() and dest_file.stat().st_size > 0:
            (w, h), status = validate_pil(dest_file)
            if status == 'ok':
                entry['status'] = 'cached-validated'
                entry['width'], entry['height'] = w, h
                entry['bytes'] = dest_file.stat().st_size
                entry['note'] = 'cached file PIL-verified'
                log(f'Cached valid {image_name}')
            else:
                entry['status'] = 'invalid-cache'
                entry['note'] = f'cached invalid: {status}'
                log(f'Cached invalid {image_name}: {status}')
        else:
            time.sleep(INTERVAL)
            size, status = fetch_image(src_url, dest_file)
            if status == 'ok':
                (w, h), vstatus = validate_pil(dest_file)
                if vstatus == 'ok':
                    entry['status'] = 'downloaded-validated'
                    entry['width'], entry['height'] = w, h
                    entry['bytes'] = size
                    entry['note'] = 'downloaded and verified'
                else:
                    entry['status'] = 'download-invalid'
                    entry['note'] = f'PIL verify failed: {vstatus}'
            elif status == 'global-stop-429':
                entry['status'] = 'skipped-global-stop'
                entry['note'] = 'download stopped due to 429'
                stop_all = True
            elif status == 'forbidden':
                entry['status'] = 'skipped-forbidden'
                entry['note'] = 'HTTP 403 forbidden'
            else:
                entry['status'] = 'download-failed'
                entry['note'] = status
        if entry.get('width') and entry.get('height') and dest_file.exists():
            if not thumb_dest.exists() or thumb_dest.stat().st_size == 0:
                if make_thumb(dest_file, thumb_dest):
                    log(f'Thumb created {image_name}')
                else:
                    log(f'Thumb failed {image_name}')
            else:
                # verify existing thumb
                try:
                    with Image.open(thumb_dest) as im:
                        im.verify()
                except Exception:
                    if make_thumb(dest_file, thumb_dest):
                        log(f'Re-created thumb {image_name}')
        manifest['items'].append(entry)
    # save manifest
    try:
        with open(MANIFEST_PATH, 'w', encoding='utf-8') as f:
            json.dump(manifest, f, indent=2, ensure_ascii=False)
    except Exception as e:
        log(f'Manifest write error: {e}')
    # contact sheet
    valid_entries = [e for e in manifest['items'] if e.get('width') and e.get('height')]
    create_contact_sheet(valid_entries)
    # write log file
    log_path = BASE / 'reproduce.log'
    with open(log_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(log_lines))
    print(f'Log: {log_path}')
    print(f'Manifest: {MANIFEST_PATH}')
    print(f'Contact sheet: {CONTACT_SHEET}')
    print('Done. No claim of manual review; temporary staging only.')

if __name__ == '__main__':
    main()
